### ISSUE TITLE
Are you still interested in maintaining this?

### ISSUE THREAD

**Issue by barrucadu** [reinerp/indexed#4]
I've recently discovered the utility of indexed monads, and it's a shame that this package doesn't use polykinds (#1).

As it's been some years since the last release, and approaching a month since the current issues were opened, I was wondering if you were still interested in maintaing this package? If not, I'd be happy to take it off your hands.

**Comment by lspitzner** [comment]
Bump; i also need polykinds.

**Comment by schernichkin** [comment]
+1 for polykinds.

**Comment by reinerp** [comment]
My apologies for the delay. I am now reviewing all issues filed here.

Polykinds support makes sense, with one possible concern: we lose Haskell98 support. Indeed, that was the original motivation behind splitting into 'indexed' and 'indexed-extras'.

From reading the Polykinds documentation it seems I need to require Polykinds support at the declaration site (of the type or typeclass), which affects all callers, even ones who don't need it. Is there a technical way around this?

If there's no technical solution, then I suspect we may as well give up Haskell98 support, but it would be helpful if someone with more experience about polykinds could chime in.

**Comment by barrucadu** [comment]
I don't think there is a way around requiring PolyKinds at the declaration site. Although it doesn't create an _incompatibility_ with Haskell98, as a Haskell98 implementation will just see `{-# LANGUAGE PolyKinds #-}` as a comment and ignore it.

**Comment by reinerp** [comment]
Thanks for the suggestion. I've done it in a backwards-compatible way in ca1cb0f268fe1cd03df5e047fac124f55cf95066.
